#!/usr/bin/env python3
"""
Generate a list of Databricks notebook .py files for ruff exclusion.

Databricks notebooks saved as .py use magic commands (%pip, %run, %sql, etc.)
that are not valid Python syntax. Ruff cannot parse these files, producing
cascading false-positive errors. This script finds all such files so they can
be excluded from linting.

Usage:
  python scripts/generate_ruff_notebook_excludes.py          # print paths
  python scripts/generate_ruff_notebook_excludes.py --toml   # print as ruff exclude array
"""

import argparse
import sys
from pathlib import Path

NOTEBOOK_HEADER = "# Databricks notebook source"


def find_notebook_files(root: Path) -> list[str]:
    """Return relative paths to all Databricks notebook .py files."""
    notebooks = []
    for py_file in sorted(root.rglob("*.py")):
        # Skip already-excluded directories
        parts = py_file.parts
        if ".venv" in parts or "venv" in parts:
            continue
        try:
            with open(py_file, encoding="utf-8") as f:
                first_line = f.readline().rstrip()
            if first_line == NOTEBOOK_HEADER:
                notebooks.append(str(py_file.relative_to(root)))
        except (OSError, UnicodeDecodeError):
            continue
    return notebooks


def main() -> None:
    parser = argparse.ArgumentParser(description="Find Databricks notebook .py files")
    parser.add_argument("--toml", action="store_true", help="Output as TOML array for .ruff.toml")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    notebooks = find_notebook_files(root)

    if not notebooks:
        print("No Databricks notebook .py files found.", file=sys.stderr)
        sys.exit(0)

    if args.toml:
        print("# Auto-generated by scripts/generate_ruff_notebook_excludes.py")
        print("# Databricks notebook .py files with magic commands that ruff cannot parse.")
        print("extend-exclude = [")
        for nb in notebooks:
            print(f'    "{nb}",')
        print("]")
    else:
        for nb in notebooks:
            print(nb)


if __name__ == "__main__":
    main()
